-- Keybinds / navigation / plugin-usage cheatsheet.
-- Open with <leader>k or :Keys. Reuses the float renderer from the motions
-- cheatsheet so both look and behave the same.
local cheatsheet = require 'config.cheatsheet'

local M = {}

M.lines = {
  ' Keybinds, navigation & plugins      <leader> = Space     (q / <Esc> close)',
  ' ═════════════════════════════════════════════════════════════════════════',
  ' Scroll this sheet with j/k or the mouse. Every mapping in the config is here.',
  '',
  ' LEADER MENUS — press <leader> then the letter; which-key shows the rest',
  '   e Explorer      f Find files    s Search        c Code',
  '   g Git           h Harpoon       b Buffer        t Tabline (tabs)',
  '   d Debug         x Trouble       u UI toggles    w Window',
  '   q Diag→loclist  m Motions       k This sheet    ? All keymaps',
  '',
  ' ── FIND  <leader>f ─────────────── SEARCH / GREP  <leader>s ────────────────',
  '   ff files                         sg grep (live regex)   sw word under cursor',
  '   fr recent files                  sf fuzzy in files      sk keymaps',
  '   fb open buffers                  sd diagnostics (buf)   sr resume last picker',
  '   fn nvim config files             sh help tags           s/ lines in buffers',
  '                                    ss document symbols    sb current buffer',
  '                                    sx replace word under cursor (whole file)',
  '   <leader>/  project grep (live)   ss/sw/sd also power the LSP + diag pickers',
  '',
  ' ── MOVEMENT & SCROLL (no leader) ──────────────────────────────────────────',
  '   h j k l      left/down/up/right     (arrows just nag you to use hjkl)',
  '   j k          move by SCREEN line when wrapped; 5j etc. stays line-wise',
  '   <C-d> <C-u>  half-page down / up, cursor kept centred',
  '   n  N         next / prev search match, centred + fold opened',
  '   %            jump to matching bracket',
  '   <C-h/j/k/l>  move focus between split windows',
  '   <Esc>        clear the search highlight',
  '',
  ' ── EDITING (no leader unless shown) ───────────────────────────────────────',
  '   <C-s>            save file (works in normal AND insert mode)',
  '   <A-j> / <A-k>    move line (normal/insert) or selection (visual) down/up',
  '   <  >  (visual)   shift indent and KEEP the selection (repeatable)',
  '   J                join line below, cursor stays put',
  '   d  D  x          delete to the BLACK HOLE — no yank, register untouched',
  '   <leader>dd       classic cut: delete INTO the register (the old d)',
  '   y                the only thing that fills the register now',
  '   <leader>p (vis)  paste over selection WITHOUT clobbering the clipboard',
  '   <leader>sx       replace the word under the cursor across the whole file',
  '   gcc · gc{motion} · gbc     toggle line / motion / block comment',
  '   sa{motion}{c} · sd{c} · sr{old}{new}   add / delete / replace surround',
  '   vif/vaf function · vic/vac class · vio/vao if-or-loop   (treesitter objects)',
  '   (full motion + text-object reference lives on <leader>m)',
  '',
  ' ── COMPLETION  (insert mode, mini.completion) ─────────────────────────────',
  '   (auto-popups as you type)     <C-Space> force LSP complete   <A-Space> buffer words',
  '   <C-n> / <C-p>  next / prev    <C-y> accept    <C-e> cancel the popup',
  '   <C-x><C-f> path complete      <C-x><C-o> manual LSP    docs+signature auto-show',
  '',
  ' ── LSP  (buffer-local; active once a server attaches) ─────────────────────',
  '   grd definition   grr references    gri implementation   grt type definition',
  '   grn rename       gra code action   grs document symbols grw workspace symbols',
  '   grc declaration  K  hover docs      ]d / [d  next / prev diagnostic',
  '   gra applies a fix OR refactor; Visual-select first for extract-method etc.',
  '   <leader>cf format buffer           <leader>cd line diagnostics (float)',
  '   <leader>q  send diagnostics to the location list',
  '   <leader>uh toggle inlay hints      <leader>ul toggle LSP for this buffer',
  '',
  ' ── DIAGNOSTICS vs TROUBLE ─────────────────────────────────────────────────',
  '   Diagnostics = the problems themselves (from LSP + treesitter): inline text,',
  '     <leader>cd float, <leader>q loclist, <leader>sd fuzzy list, ]d/[d jump.',
  '   Trouble = a nicer PANEL over that same data (and refs, symbols, quickfix):',
  '     xx workspace diag   xb buffer diag    xs symbols   xr LSP defs/refs',
  '     xl location list    xq quickfix       xt todo comments',
  '   In a Trouble/Todo panel: <CR> jump · q close · same <leader>x_ key toggles it.',
  '',
  ' ── GIT  <leader>g  (in a tracked file) ────────────────────────────────────',
  '   gs stage hunk (or visual selection)   gp preview hunk',
  '   gr reset hunk (or visual selection)   gb blame line   gB blame whole file',
  '   ga stage whole buffer                 gd diff against index',
  '   gx reset (discard) buffer             gl diff against last commit',
  '   ]c / [c  next / prev changed hunk     <leader>ub blame toggle · <leader>ud deleted',
  '',
  ' ── SPELL CHECK  (toggle with <leader>us) ──────────────────────────────────',
  '   ]s / [s   next / prev misspelled word     z= suggest corrections (pick a number)',
  '   zg add word to dictionary (good)          zw mark word as wrong',
  '   zug / zuw undo the last zg / zw            zG / zW same but session-only',
  '',
  ' ── BUFFERS & TABLINE  <leader>t  (the tab bar) ────────────────────────────',
  '   [b ]b or <A-h> <A-l>  prev / next buffer      <A-1>..<A-9> jump to buffer N',
  '   <leader>t1..t9 jump · t0 last · tj pick       <leader>bw close (keep layout)',
  '   t[ / t] move buffer · tp pin                  tw close · tx pick-close',
  '   to close others · th / tl close left / right  ts / te sort by dir / ext',
  '',
  ' ── WINDOWS & TERMINAL  <leader>w ──────────────────────────────────────────',
  '   <leader>- split below · <leader>| split right   <C-h/j/k/l> move focus',
  '   wd close · wo close others · w= equalize        <C-arrows> resize window',
  '   <C-/> (or <C-_>) toggle floating terminal       <Esc><Esc> leave terminal mode',
  '',
  ' ── HARPOON  <leader>h ─────────────────────────────────────────────────────',
  '   ha add file · hm quick menu · hn next · hp prev   <leader>1-4 jump to file 1-4',
  '',
  ' ── UI TOGGLES  <leader>u ──────────────────────────────────────────────────',
  '   ub git blame line   uc treesitter context   ud git deleted   uh inlay hints',
  '   ui indent guides    ul LSP (this buffer)     uw word wrap     us spell check',
  '   u<Space> show whitespace',
  '',
  ' ── DEBUG  <leader>d  (nvim-dap; C#/.NET wired) ────────────────────────────',
  '   <F5> start/continue · <F1> step into · <F2> step over · <F3> step out',
  '   db breakpoint · dc conditional breakpoint · du toggle UI · dr toggle REPL',
  '',
  ' ── PLUGIN USAGE & CLOSING PANELS ──────────────────────────────────────────',
  '   neo-tree (<leader>e):  a add · d delete · r rename · c copy · x cut · p paste',
  '   fzf-lua picker:        type to filter · <Tab> multi-select · <C-q> → quickfix',
  '   Trouble / Todo panel:  q or the same <leader>x_ toggle key closes it',
  '   which-key popup:       <Esc> closes it (or just pick a key)',
  '   these cheatsheets:     q or <Esc>          floating terminal: <C-/>',
  '',
  ' ── COMMANDS  (type : then the name) ───────────────────────────────────────',
  '   :Keys  :Cheatsheet     these two cheatsheets (also <leader>k / <leader>m)',
  '   :Mason                 install / manage LSP servers, formatters, adapters',
  '   :MasonToolsInstall     install everything on the ensure-installed list',
  '   :checkhealth           diagnose the setup (e.g. :checkhealth vim.lsp)',
  '   :Trouble <mode>        diagnostics / symbols / lsp / loclist / qflist / todo',
  '   :Neotree toggle        file explorer (same as <leader>e)',
  '   :TodoTrouble  :TodoQuickFix    list TODO / FIXME / HACK / NOTE comments',
  '   :ConformInfo           show which formatters apply to this buffer',
  '   :Gitsigns <action>     run any gitsigns action by name',
  '   :TSInstall <lang>  :TSUpdate     add / update a treesitter parser',
  '   :VimBeGood             vim-motion practice game',
  '   :lua vim.pack.update() update plugins (shows a diff to confirm)',
  '',
  ' Reminder: <leader>? lists every leader mapping live (which-key); <leader>m = motions.',
}

function M.open()
  cheatsheet.open_float(M.lines, ' Keybinds & navigation ')
end

vim.api.nvim_create_user_command('Keys', M.open, { desc = 'Keybinds / navigation / plugin cheatsheet' })
vim.keymap.set('n', '<leader>k', M.open, { desc = '[k]eybinds cheatsheet' })

return M
